version: '3'
services:
  manning-client:
    build:
        context: .
        dockerfile: DownloadManningBook/Dockerfile
    environment:
      BOOK_URL: https://livebook.manning.com/book/cloud-native-patterns
      RABBITMQ_URL: rabbitmq
    volumes:
      - ./data:/app/output/out
      - data8:/app/output/chapters
    depends_on:
      rabbitmq:
        condition: service_healthy    

  consumer:
    build:
        context: .
        dockerfile: ConsumerUnlockProcess/Dockerfile
    environment:
      BOOK_URL: https://livebook.manning.com/book/cloud-native-patterns
      RABBITMQ_URL: rabbitmq
    volumes:
      - data8:/app/output/chapters
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      
volumes:
  data8: